version: '3'
services:
  books_api:
    container_name: books_api
    build:
      context: ./services/books
      dockerfile: Dockerfile
    volumes:
      - './services/books:/usr/src/app'
    ports:
      - 5002:5002
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres_dev:postgres_dev@books_db:5432/books_dev
      - DATABASE_TEST_URL=postgresql://postgres_dev:postgres_dev@books_db:5432/books_test
    depends_on:
      - books_db
    links:
      - books_db

  books_db:
    container_name: books_db
    build:
      context: ./services/books/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_dev
      - POSTGRES_PASSWORD=postgres_dev
